// This file is usually generated by `diesel print-schema`
// Example for users table

table! {
    users (id) {
        id -> Int4,
        username -> Varchar,
        email -> Varchar,
        password_hash -> Varchar,
    }
}
