[dependencies]
dotenv = "0.15"
[dependencies]
diesel = { version = "2.1", features = ["postgres", "r2d2", "chrono"] }
diesel_migrations = "2.1"
chrono = "0.4"
[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
